export type Track = {
  number: number;
  title: string;
  lyrics: string[];
};

export type ReleaseLink = {
  label: string;
  href: string;
};

export const album = {
  title: "A través",
  year: 2026,
  releaseDate: "30 de abril de 2026",
  cover: "/album/atraves-cover.png",
  description: "Trío de rock de Montevideo, Uruguay.",
  spotifyAlbumId: "6JCqwuLX3KsUps8wsncgaQ",
  links: [
    {
      label: "Spotify",
      href: "https://open.spotify.com/album/6JCqwuLX3KsUps8wsncgaQ",
    },
    {
      label: "YouTube Music",
      href: "https://music.youtube.com/playlist?list=OLAK5uy_l8s5rjSDk6nmDhcwQ4Wgq7UiZpJYn0CCo",
    },
    {
      label: "Bandcamp",
      href: "https://mariapuniales.bandcamp.com/album/a-trav-s",
    },
    {
      label: "YouTube",
      href: "https://www.youtube.com/@MariaPu%C3%B1alesBanda",
    },
  ] satisfies ReleaseLink[],
  credits: [
    "Grabado, editado y masterizado en Estudio Flores, entre marzo de 2025 y abril de 2026.",
    "Drum doctor: Gastón Vivas",
    "Isabel Palomeque: coros en 4, 5 y 8",
    "Agustín García: guitarra eléctrica en 1 y 5",
  ],
  tracks: [
    {
      number: 1,
      title: "Un eco",
      lyrics: [
        "Nada oí cuando retó el mar",
        "Nada oí cuando gruñó el mar",
        "Rosado era su pestañear",
        "Lila era su gargantear",
        '"¿Por qué corriste?',
        '¿A quién te llevaste?"',
        "No quiero saber nada de lejos",
        "No quiero ser el testigo del eco",
        "Del terco pasto al arenal",
        "El cielo abierto quiso augurar",
        '"De los finales es el final"',
        "No pude oír preguntar al mar",
        '"¿Por qué corriste?',
        '¿A quién te llevaste?"',
        "No quiero saber nada de lejos",
        "No quiero ser el testigo del eco",
        "No quiero saber nada de lejos",
        "No quiero saber nada de lejos",
        "Todo vi cuando se fue el mar",
        "Nada fui cuando bajó el mar",
      ],
    },
    {
      number: 2,
      title: "La nota en la heladera",
      lyrics: [
        "Los codos en las piernas",
        "La mente al más allá",
        "Algo en la densa espera",
        "Que se iba a terminar",
        "Se escondió",
        "Fundido con la niebla",
        "Que va del más acá",
        "En manos de la piedra",
        "Cerca de algún lugar",
        "Se perdió",
        "Las campanas se quejan",
        "En gritos de metal",
        "La nota en la heladera",
        "No deja de sonar",
        "Se alejan las sirenas",
        "Envidian su cantar",
        "La nota en la heladera",
        "No deja de sonar",
        "Los truenos verdes quiebran",
        "Son suaves, son verdad",
        "La nota en la heladera",
        "No deja de sonar",
      ],
    },
    {
      number: 3,
      title: "Acá o en cualquier pueblo",
      lyrics: [
        "Otra vez fui",
        "Y los cuervos en París",
        "Queriéndose volar",
        "Queriendo partir",
        "¿Por qué no venís",
        "Conmigo a Berlín",
        "A hacernos golpear",
        "Por el muro y reír",
        "Otra vez?",
        "Acá o en Montevideo",
        "Otra vez acá o en Montevideo",
        "Escuchemos La Paloma en Malasaña",
        "Escuchemos a los Problems en la Aduana",
        "Otra vez fui",
        "Y los cuervos en París",
        "Queriendo devorar",
        "Queriendo parir",
        "¿Por qué no venís",
        "Conmigo a El Tahrir?",
        "¿Por qué no inundar",
        "El Nilo y segar",
        "Otra vez?",
        "Acá o en Montevideo",
        "Otra vez acá o en cualquier pueblo",
        "Otra vez acá acá",
        "Otra vez acá",
      ],
    },
    {
      number: 4,
      title: "De largo",
      lyrics: [
        "No es solo el vapor",
        "Que azota la ciudad",
        "Y la hace verse abierta",
        "No es tanto la flor",
        "Ni el olor a mar",
        "Ni la bruma amarillenta",
        "No es el estertor",
        "Desde el humo gris",
        "Que a nadie despierta",
        "No es una canción",
        '"Che sarà sarà"',
        "Ni los cuerpos que pasan de largo",
        "Ni los cuerpos que pasan de largo",
        "Ni los cuerpos que pasan de largo",
        "Ni los cuerpos que pasan de largo",
        "No es resplandor",
        "El del Templo inglés",
        "U orar que se desprenda",
        "No es un corazón",
        '"Che sarà sarà"',
        "Ni los puertos que pasan flotando",
        "Ni los puertos que pasan flotando",
        "Ni los puertos que pasan flotando",
        "Ni los puertos que pasan flotando",
        "Ni los cuerpos que pasan de largo",
        "Ni los cuerpos que pasan de largo",
        "Ni los puertos que pasan flotando",
        "Ni los puertos que pasan flotando",
      ],
    },
    {
      number: 5,
      title: "Veo a través",
      lyrics: [
        "Las manos de herrumbre",
        "En ramas florecen",
        "Las luces azules",
        "Y rojas son peces",
        "Las paredes tibias",
        "En baba empañan",
        "Veinte sombras chinas",
        "De nucas quebradas",
        "Veo a través",
        "Veo a través",
        "Veo a través",
        "Veo a través",
        "Miradas me llaman",
        "Yo no sé qué busco",
        "Entre las espadas",
        "Y un pulpo de rulos",
        "Y nubes de nombres",
        "Y almas en falso",
        "Y lenguas de acoples",
        "Y lirios en labios",
        "Veo a través",
        "Veo a través",
        "Veo a través",
        "Veo a través",
        "No veo más allá",
        "Pero veo a través",
        "No veo más allá",
        "Pero veo a través",
      ],
    },
    {
      number: 6,
      title: "Superhéroe",
      lyrics: [
        "Como un Tristán post feria",
        "Como galería en Yaguarón",
        "Como un perro sin su dueña",
        "Como debería sentirse Dios",
        "Como un superhéroe en un cuento de terror",
        "Como un superhéroe en un cuento de terror",
        "Como Asterión en laberinto",
        "Sin Ariadnas que apresar",
        "Como de hormigas su reina",
        "Como guarda en terminal",
        "Como un superhéroe en un cuento de terror",
        "Como un superhéroe en un cuento de terror",
      ],
    },
    {
      number: 7,
      title: "Si te sirve",
      lyrics: [
        "Si te sirve no es todo tu culpa",
        "No es todo tu culpa",
        "No es todo tu culpa",
        "No es todo tu",
        "No te sirve? Digo que es mi culpa",
        "Digo que es mi culpa",
        "Digo que es mi culpa",
        "Digo que es mi",
      ],
    },
    {
      number: 8,
      title: "Primavera",
      lyrics: [
        "Suben del bajo",
        "Y bajan del alto",
        "Cantos robados",
        "Amontonados",
        "Surcan el lago",
        "Viajan callados",
        "Nos enfría",
        "Y se congela",
        "Proserpina",
        "Primavera",
        "Los meses albos",
        "Los años calmos",
        "Bosques y prados",
        "Abandonados",
        "Nos enfría",
        "Y se congela",
        "Proserpina",
        "Primavera",
        "Nos enfría",
      ],
    },
  ] satisfies Track[],
} as const;

export const singles = [
  {
    title: "Acá o en cualquier pueblo",
    cover: "/album/aoecp-cover.jpeg",
    note: "Incluido en A través",
  },
  {
    title: "De largo",
    cover: "/album/delargo-cover.jpg",
    note: "Incluido en A través",
  },
] as const;

export const videos = [
  {
    title: "Acá o en cualquier pueblo",
    youtubeVideoId: "0fyjfWmUhkw",
  },
] as const;
